### PR TITLE
Updated script comments

### PR DESCRIPTION
**Pull request by Poshwosh**
- Added "Description:" tag at the beginning of scripts, and below them is a small explanation of what the script does.
- Added a brief description to scripts that did not have one.
- Reworded a few existing descriptions.
- Added "Configuration:" tag with 'how-to-edit' steps if a script has a configurable variable (freezetimeofday, renderdistance, etc).
- Added "Walkthrough:" tag to scripts that have one,
- Renamed ClientSideDevCat to devCATEffects.
- Updated ClientSideDevCat to devCATEffects in coalesce.txt.
- Updated PartyChatMarketFilter with new filters.

I started all of this because some scripts don't have a proper description of what they do, but then I ended up improving on all of them.

I'm sorry if it's too much to look through @cursey, it's mostly just wording though! No changes to code whatsoever, with the exception of coalesce.txt & partychatmarketfilter.js

### CODE REVIEW

**Comment by cursey** [comment]
I am worried about renaming scripts because people who've already downloaded kanan will likely end up with duplicates. 

I need to come to terms with this.

**Comment by inklit** [comment]
@cursey When I update kanan, I completely delete everything and reclone it from Git.
I would not have duplicates since I overwrite it all. It's far easier to do this after all.
I imagine a lot of others do the same.

**Comment by Poshwosh** [comment]
I actually update from the master branch.

However when I update, it detects if I renamed any files, then it deletes it and creates a new one. 

http://i.imgur.com/FyHaQVG.png

I imagine it would do the same here.

**Comment by Rydian** [comment]
I delete everything except the data folder and disable.txt just in case anyways, because other methods of updating would be more effort due to the nature of toggling mods.

**Comment by cursey** [comment]
I'm not worried about those of us who are active on GitHub but the people who download kanan once as a .zip of the master branch and update by just occasionally overwriting their old kanan folder with the new one.

Can you add the old filenames to `disabled.txt`. That's an easy way to fix this issue :)

**Pull request closed without merging**
