### PR TITLE
Wait for client if it isn't already running

### PR DESCRIPTION
**Pull request by ghost**
The extra sleep because the client needs time to to unpack before the patches are applied, otherwise the client will crash.

### CODE REVIEW

**Comment by ghost** [comment]
Actually, this seems to crash if it waits too long, though I don't know why.

**Comment by cursey** [comment]
I quickly skimmed over frida's python implementation to see if they expose a way to check if a process with a specific name is running and nothing stood out to me.  They have very little documentation on the python side of things so I think the way you are doing it is the only/correct way to do it.

I'll merge the PR for now even though it's not ideal but the instructions in the readme are going to stay telling people to run it after mabi has started until the crashes are addressed (by us or frida).

**Comment by ghost** [comment]
In hopes of getting the issue fixed, I created an issue in their repo: https://github.com/frida/frida-python/issues/84 :+1:

**Comment by cursey** [comment]
I fixed it.

**Pull request merged**
