### PR TITLE
Create LogOutInConversation.js

### PR DESCRIPTION
**Pull request by Rydian**
Stupid Baltane NPCs getting me stuck.

### CODE REVIEW

**Comment by ghost** [comment]
How about changing channels, too? 👍

**Comment by Rydian** [comment]
Yup that works too.

**Comment by cursey** [comment]
Using this signature `84 C0 74 19 B8 ? ? ? ? 8B 4D F4 64 89 0D ? ? ? ? 59 5F 5E 5B 8B E5 5D C2 04 00` is unique (doesn't return two results).

**Comment by Rydian** [comment]
That signature returns no results on my end.

`84 C0 74 19 B8 ? ? ? ? 8B 4D F4 64 89 0D ? ? ? ? 59 5F 5E 5B 8B E5 5D C2`

Is as far as it matches, mine is giving a return value of 0C instead of yours giving 04.

EDIT: And that may be targeting the other piece of code anyways, let me double check.

**Comment by cursey** [comment]
Uhh, if you're scanning using CE you might need to double up the ?'s although single ? wildcards are valid for kanan.

edit:
Yeah, I tested `84 C0 74 19 B8 ?? ?? ?? ?? 8B 4D F4 64 89 0D ?? ?? ?? ?? 59 5F 5E 5B 8B E5 5D C2 04 00` in CE and it worked 😮

**Comment by Rydian** [comment]
Single ones work, I just use doubles because it keeps alignment in text editors.

Fired up the client clean to test, and for some reason CE is returning the AOB as successful (with the right address) even though the disassembler, memory view, and table view show C2 0C (first two bytes of the return opcode) on my machine while the sig is looking for C2 04.  Might be a bug in CE, going to see if 6.5.1 fixes it.

EDIT: I updated CE, and _with the same client session_ the ret is showing 04 now, so it may have been one of my previous settings or a bug in 6.5.

**Comment by cursey** [comment]
@QewQew you could already change channels while chatting with NPC's from `NoChannelMoveDenial.js`.

**Comment by ghost** [comment]
Oh, I never even noticed that patch. 👍 It appears you can, haha. My apologies.

**Pull request merged**
